name: CitizensShop
version: 1.0
author: Alaskalix, Fred46
main: alaskalix.main.Main
description: Gestionnaire de shop pour npc
api-version: 1.14
depend: [Citizens, Vault]
commands:
  createShop:
    description: create a npc shop
    permission: citizensShop.admin
  ctzShop:
    description: add or remove items from a shop
    permission: citizensShop.admin